# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - test
  - release
#  - deploy
#  - cleanup

build:
  stage: build
  script:
    - npm install --verbose
    - npm run build
  tags:
    - npm

test:
  stage: test
  script:
    - npm run test
  tags:
    - npm

release:
  stage: release
  script:
    - npm version --no-git-tag-version "$CI_BUILD_TAG"
    - npm publish --verbose
  tags:
    - npm
  only:
    - tags
